### ISSUE TITLE
[fix] 북마크여부 API query param 변경 적용

### ISSUE THREAD

**Issue by NaayoungKwon** [Eagle2gle/wealth-marble-frontend#135]
## 🤷‍♂️ Description
(내용 요약)

이전에 요청했던 북마크 여부를 확인하기 위해 query parameter에 userId를 넣는 방식으로 수정했습니다.
이부분이 아직 반영이 안된 것 같아 확인 부탁드립니다. postman에도 반영했습니다.

- [ ] {{ip}}:{{port}}/api/cahoots?status=ongoing

<img width="393" alt="KakaoTalk_Snapshot_20230408_010606" src="https://user-images.githubusercontent.com/34162358/230640566-f92162da-37fc-49da-8475-3e12fbcc4322.png">

장소별 추천 휴양지는 반영 확인했습니다.

**Comment by m4nd4r1n** [comment]
@NaayoungKwon 
#134 에서 반영되었는데 아직 production으로 배포되지 않았습니다.

**Comment by NaayoungKwon** [comment]
@m4nd4r1n 아아 확인 감사합니다. 그럼 이 이슈는 닫아둘게요!
